CREATE TABLE CUSTOMER (
 ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 FIRSTNAME VARCHAR(15), 
 LASTNAME VARCHAR(15),
 PRIMARY KEY (ID)
 );
 
 INSERT INTO CUSTOMER VALUES(default, 'John', 'Doe');
 INSERT INTO CUSTOMER VALUES(default, 'Joe', 'Jones');
 INSERT INTO CUSTOMER VALUES(default, 'Sally', 'Smith');


Create table dept(
deptid int primary key,
dname varchar(20) ,
location varchar(20)
);

create table employee(
empid int primary key,
ename varchar(30),
sal decimal(9,2),
doj date,
deptid int references dept(deptid));

insert into dept values(10,'HR','Mumbai');
insert into dept values(11,'Sales','Pune');
insert into dept values(12,'Purchase','Pune');
insert into employee values(101,'Shrilata',12345.00,'12/11/2110',12);
insert into employee values(102,'Anita',11111.00,'12/11/2009',11);
insert into employee values(104,'Kavita',22222.00,'12/11/2110',11);
insert into employee values(105,'Sunita',5555.00,'12/11/2110',10);
